### PR TITLE
Merge Sort

### PR DESCRIPTION
**Pull request by sohm1112**
Kindly add this pr to your repository

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @DanielGoldfarb, this user is going around to several repos (mine included) that have the `hacktoberfest` topic and spamming them, trying to get 4+ PRs for Hacktoberfest. If you could please [apply a `spam` label to PRs like this that you see](https://hacktoberfest.com/participation/#spam), it'll disqualify that individual from Hacktoberfest entirely and discourage this behavior in future Hacktoberfests.

Thank you! 🤝

**Comment by DanielGoldfarb** [comment]
@crweiner 
Chandler ... Noted.  Thanks for the heads up.  Much appreciated.  --Daniel

**Comment by DanielGoldfarb** [comment]
@crweiner 
Chandler ... Interesting ... looks like a group of friends have made repositories that they all simply contribute to for the sake of hacktoberfest spamming:  https://github.com/ossamamehmood/Hacktoberfest2022/pulls?q=is%3Apr+is%3Aclosed   since they are, what appears to be, colluding, they are not marked spam.

**Comment by crweiner** [comment]
Hey @DanielGoldfarb! 👋 Those repos have been excluded from Hacktoberfest entirely by not following the rules. No PRs there will count, no matter what the maintainers do.

If you see a purposely spammy repo, it can be [reported to the Hacktoberfest Team here](https://hacktoberfest.com/report/). Note, you'll need to be registered (for free) for Hacktoberfest yourself to submit a spam repo report. The Hacktoberfest Team reviews these reports and then bans entire repos if they are not playing by the rules.

The second layer of moderation is dependent upon legit repo maintainers like us to label PRs as either `invalid` or `spam`, depending on the severity. The `spam` label is a two strikes and you're out consequence, where that individual is excluded from Hacktoberfest entirely. The `invalid` label on a PR is when something isn't quite right, but not outright spam. 

If you *do* receive a good PR (in a repo that has the `Hacktoberfest` tag), that person can get credit for their PR when you either merge it, apply the `hacktoberfest-accepted` label to their PR, or provide an approving code review. 😊

Hope that helps! 👍

**Comment by DanielGoldfarb** [comment]
@crweiner
Hey Chandler,   Thanks for the info!  Definitely helps.   This is my first time being involved with Hacktoberfest.   It's a nice idea.   I recently merged a hacktoberfest contribution for an enhancement that some of my users had been requesting (but I had been too busy to do it myself).  Hacktoberfest is a nice way to get people to notice the repository. 
All the best.   --Daniel

**Comment by crweiner** [comment]
@DanielGoldfarb
Hacktoberfest is wonderful, and thank you for opting-in to be a part of it! 🎉 Very happy to hear you got some meaningful contributions too! 😊

Moadim L'Simcha! 🍋🌴

**Comment by DanielGoldfarb** [comment]
@crweiner,    מאחלת לך שנה טובה ומתוקה

**Comment by DanielGoldfarb** [comment]
@crweiner 
Chandler,
Perhaps you can help or guide me.  I see where I can report a repository that is not in "compliance" with hacktoberfest, however not sure what to do about users who are simply behaving suspiciously.  What I mean is that I have had a couple instances of users who simply go into the Issues that I have labelled hacktoberfest and add a comment "please assign this to me."  What is suspicous is (1) there is no other discussion (2) when I ask what their plan is for implementation or of they need any guidance there is no response (3) sometimes the same user will put the "please assign to me" comment in severa issues, and in one case the issue was not even requesting anything (the issue was simply a user asking a question).  Is there some benefit or hack for people to simply get issues "assigned" to them?  Or is there a way to report such users to be investigated?

**Comment by crweiner** [comment]
@DanielGoldfarb , there's no way to currently report individual users except for labeling their PRs as `spam` or `invalid` as necessary. 

There is also no need to assign any Issues, and there is no benefit any participants get by having an Issue assigned to them. 

There was a scenario 2 years ago that caused a major shift in the Hacktoberfest rules where repos had to explicitly _opt in_ via the `Hacktoberfest` label due to a[ mass spamming incident that occurred as a result of a YouTuber encouraging spam for the sake of a shirt](https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama)... I think that these individuals asking for Issues to be assigned are just following some playbook as in 2020 to try and get a shirt. 😒 

The "assigning Issues" request just appears to be a temporary annoyance for now. You may want to add something in your [Contributing file](https://github.com/matplotlib/mplfinance/blob/master/CONTRIBUTING.md) saying that Issues are not assigned during Hacktoberfest, but I highly doubt that it'll stop those posts because they clearly aren't reading that in the first place... 😐

**Pull request closed without merging**
