### PR TITLE
Add Point and Figure parameter to customize number of boxes needed to reverse the trend

### LINKED ISSUE #368: Point and figure [pnf] - Reversal param
Hello,

Is it possible to change the PNF param "reversal" the same way as i can do with "box_size"? Is it even possible?

`mpf.plot(df, type='pnf', pnf_params=dict(box_size=7))`

### PR DESCRIPTION
**Pull request by coffincw**
The reversal was previously configured to be two boxes.  With this new parameter, you can customize the reversal value as long as it's >= 2 and the product of the box_size and the reversal does not exceed 30% of the close price range of the dataset.

Here is an example:
`mpf.plot(df,type='pnf',pnf_params=dict(box_size='atr',atr_length='total', reversal=3),mav=(4,6,8),volume=True)`

reversal param example

Closes #368

### CODE REVIEW

**Comment by DanielGoldfarb** [comment]
@coffincw 
Caleb,  Can you explain to me why we cannot support reversal=1 ?

I observed on the Bloomberg system that they allow reveral to be any integer from 1 to 9.   

I also observed that, for some charts, when the reversal amount gets large (for example reversal=7, or 8 or 9) then the chart displays only a single column, or a just a few columns, and the charts for reversal=7 or 8 or 9 are all identical.   Other charts do show *some* difference for the larger reversal settings.  At any rate, being very much a novice at PnF charts, I would like to understand what the limitations at both the low and the high end of possible reversal settings.  Thanks. --Daniel

**Comment by coffincw** [comment]
> @coffincw
> Caleb, Can you explain to me why we cannot support reversal=1 ?
> 
> I observed on the Bloomberg system that they allow reversal to be any integer from 1 to 9.
> 
> I also observed that, for some charts, when the reversal amount gets large (for example reversal=7, or 8 or 9) then the chart displays only a single column, or a just a few columns, and the charts for reversal=7 or 8 or 9 are all identical. Other charts _do show some difference for the larger reversal settings_. (Apparently the behavior depends at least somewhat on the data itself).
> 
> At any rate, being very much a novice myself at PnF charts, I would like to understand the exact nature of the limitations at both the low and the high end of possible reversal settings. Thanks. --Daniel

@DanielGoldfarb I actually wasn't sure whether the existing reversal value was 1 or 2 since it requires two full boxes of price movement in the opposite direction to switch the trend direction.  

reversal example

But since Bloomberg considers this to be reversal =1 I can easily adjust the values.

Regarding the upper limitations of the reversal value I settled on limiting the brick_size * reversal to be < 30% of the closing range, but if Bloombergs system allows reversal periods 1-9 we should probably go with that too.

Let me know what you think.

**Comment by DanielGoldfarb** [comment]
Caleb,
Please try allowing reversal periods 1-9 and test several different cases of data.  As long as there are no exceptions raised, and the plot appears reasonable, I see no reason not to allow it.  Please let me know if you run into any issues.  When you are done, I will install from your fork onto my local machine and do some testing myself.
Thanks. --Daniel

**Comment by coffincw** [comment]
> Caleb,
> Please try allowing reversal periods 1-9 and test several different cases of data. As long as there are no exceptions raised, and the plot appears reasonable, I see no reason not to allow it. Please let me know if you run into any issues. When you are done, I will install from your fork onto my local machine and do some testing myself.
> Thanks. --Daniel

Allowed for reversal values of 1-9, but I found a new bug while testing.  I'm hoping to have some time to take a look at it in the next few days.

**Comment by DanielGoldfarb** [comment]
Thanks.  Looking forward to it.

**Comment by coffincw** [comment]
It's good to fork and test.  Let me know if you run into any issues.

**Pull request merged**
