### PR TITLE
API for adding labels: `mpf.make_addplot(..., label="myLabel")`

### PR DESCRIPTION
**Pull request by alexpvpmindustry**
easy api for adding labels to `mpf.make_addplot`

image

Note:
- use panel=1 to choose the lower panel
- supported types: 'scatter', 'bar', 'line', 'step'
- NOT supported types: 'ohlc', 'candles'

see `examples/addplot_legends.ipynb` for the example notebook.

courtesy of @ppseverin for inspiration, replacing PR #277

### CODE REVIEW

**Comment by DanielGoldfarb** [comment]
@alexpvpmindustry 
Alex,
   Just took a quick look.  Beautiful job.  I'm really swamped right now, but will do my best to set aside some time early next week (Monday or Tuesday) to fully test and then merge.  In the meantime, please bump the version.
   My mind is wondering (what do you think) should we rename the kwarg to `legend_label` to be more explicit (since there are also `xlabel` and `ylabel` and an annotation can have a label)?   Or do you think it's self-explanatory as is?
                                                                                                            All the best.  --Daniel

**Comment by alexpvpmindustry** [comment]
> kwarg to `legend_label` to be more explicit
I use matplotlib alot, so `label` would be the first thing I would try.

> an annotation can have a label
That is new to me.

Either way, it would be more useful for the doc string to report all the allowed kwargs. Currently if I press shift+tab, the doc that comes out is quite useless.

**Comment by DanielGoldfarb** [comment]
If you think 'label' is more intuitive for a matplotlib user that's ok.   I know many of the matplotlib functions accept kwarg label meaning the label for the legend.   Meanwhile, if you google "matplotlib label" most of the top results are about labeling the x and y axis.  I don't feel strongly about this, but i do also want to be clear to users who may not be familiar with matplotlib.   Part of my mplfinance philosophy is to make it easy to use without knowing matplotlib (or much python) while at the same time having hooks in place for those who know matplotlib and want to access it's full power.

Regarding doc strings, the is a method you can call, `mpf.kwarg_help()` which will output information about the kwargs (from the valid kwargs table).   Perhaps I will add info about the kwarg_help() function to all of the doc strings.

**Comment by alexpvpmindustry** [comment]
> without knowing matplotlib (or much python)

sidenote: is there a way to provide kwargs suggestion/correction? like if someone input the wrong kwargs, the error at the end should say "ledgend_label" does not exist, do you mean "legend_label"? or something similar. in the docs of numpy functions, there is usually a suggestion for similar/related functions.

> mpf.kwarg_help()

that is new to me :D 

> I will add info about the kwarg_help()

maybe u can put it into a todo.

**Comment by alexpvpmindustry** [comment]
also, not sure if its somewhat related.
i think there should also be labels for `mav`s. maybe automatically generated or have the option to toggle it on or off or specify a list of strings.
but i realised `mav` was implemented all over the place, so might be a lot more difficult than doing legend_labels for `make_addplot`

**Comment by alexpvpmindustry** [comment]
@DanielGoldfarb any updates?

**Comment by DanielGoldfarb** [comment]
Will try to look at this next week or the week after that.

**Comment by DrChandrakant** [comment]
@DanielGoldfarb 
i successfully attempted 'legend_label ' add add_plot 

legend

legend 2

Following Merge PR Work Improve and creating New PR request Soon, any Suggestion for the new feature?

Script additions for 'ema' plotting #563

API for adding labels: mpf.make_addplot(..., label="myLabel") #605

**Comment by dempc6469** [comment]
checking in on the labes piece here. Any update?

**Comment by DrChandrakant** [comment]
> checking in on the labes piece here. Any update?

@dempc6469 That PR is Under review. If You Like That Concept Please Download the Source code from my mplfinance fork here: https://github.com/DrChandrakant/mplfinance/tree/mav_ytick_label

**Comment by dempc6469** [comment]
Much appreciated, Doc! Thanks!

**Comment by DanielGoldfarb** [comment]
@dempc6469 (et al)
I have a lot of mplfinance PRs to review.  Unfortunately, this week, due to other pressing projects, I won't get to any of them.  However I expect to begin reviewing mplfinance PRs again next week.

*In the meantime if you do try out* [**@DrChandrakant 's version**](https://github.com/DrChandrakant/mplfinance/tree/mav_ytick_label) I will greatly appreciate it if you can please post any feedback here.  Thank you very much!

**Comment by rudradesai200** [comment]
Can someone please merge this PR?

**Review by rudradesai200 — APPROVED** [review]
I tried this out and it works well. Can someone please merge this PR?

**Comment by DrChandrakant** [comment]
> I tried this out and it works well. Can someone please merge this PR?

I think the moderator is busy with other projects please download this  and use link here [alexpvpmindustry:master](https://github.com/alexpvpmindustry/mplfinance/tree/master)

**Comment by DanielGoldfarb** [comment]
Thanks to those who have tried this out!  
I am hoping to get back to processing the backlog of PRs sometime next week.

**Comment by DanielGoldfarb** [comment]
I've tweaked the code so that when passing a DataFrame to `make_addplot()` then it is possible to set `label` to a sequence of labels and each one will be used in order for each column of the dataframe that is plotted.

**NEXT** I need to test this new code for all relevant `make_addplot()` (i.e. line, bar, scatter) and also modify the `addplot_legends.ipynb` to have an example of doing this (as well as remove the part that suggest using multiple make_addplots instead).

**Pull request merged**
