### PR TITLE
Added the ability to create hollow candle plots

### PR DESCRIPTION
**Pull request by KenanHArik**
Hello - great library. Wanted to contribute the ability to handle hollow candle plots. I have prototyped some logic to implement this, please check it out 👍

See some background notes if needed on hollow candles here:
https://stockcharts.com/articles/mailbag/2012/11/what-the-deal-with-these-colored-filled-and-hollow-candles.html

Creating a hollow candles chart would require to command: mpf.plot(daily,type='hollow_candle',style='hollow') in the currently implemented naming.

It is lucky, perhaps, that the jupyter notebook csv has the right data patterns to be able to showcase hollow candle style. See image below of the style implemented in the notebook:

image

Implementing the hollow candle style required an additional 2 labels to the candle styles dictionary. As a result, I have updated all styles in this pull request to have matching hollow and regular colors. I'm not sure if all need to be updated, but I have implemented it that way just in case.

Please let me know if you have any questions / concerns on the pull request.

Thanks!

### CODE REVIEW

**Comment by DanielGoldfarb** [comment]
@KenanHArik 
Kenan,  This is great.  Thank you sooo much!   As you can [see here](https://github.com/matplotlib/mplfinance/issues/172) this feature was requested over six months ago.   I will try to review the code within the next day or two.   Much appreciated!  --Daniel

**Comment by KenanHArik** [comment]
My Pleasure. I did come feature request in searching whether this was a possibility :)

Look over the code, and let me know your thoughts.

Cheers,
Kenan

**Comment by DanielGoldfarb** [comment]
Hi Kenan,
Once again, thank you so much for getting involved and contributing this enhancement to mplfinance.  I have not yet reviewed all of the code, but mainly focused on the changes to `_utils.py`.  I usually wait until I'm more certain, but I have some ideas that I want to run by you to get your opinion.

The first thing, that I am relatively certain of, is that as a user I think would want to see `type='hollow_candle'` apply to any style (and not require the user to specify a hollow style).

It appears to me that perhaps you had this idea in mind too(?), based on the fact that you added `up_hollow` and `down_hollow` colors to the marketcolors section of the various style configurations; and based on your wording, that you "_have **prototyped** some logic_" and that creating hollow candles requires ... `style='hollow'` "_**in the currently implemented**_" code.  With that in mind, I'm guessing that as a first-cut/prototype you found it easiest to design a specific style to implement hollow candles.  At least, that sounds like something that I might do.

That said, I starting thinking about how how I might implement it so that the user only has to specify `type='hollow_candle'` to get hollow candles for any style.  It occured to me (and then I googled for some images to confirm) that, _most often, the body color of a hollow candle exactly matches the **face-color** of the plot_.

My initial thought was that we can figure out the face-color, in the code, and use that color for the hollow candles.  But then I thought an easier way to implement that would be to simply set the **alpha** (opacity) of the candle body color to **0.0** to make the candles see-through.  At this point I started playing with your code to see if I could make this work.  I took [**these two lines of code**](https://github.com/KenanHArik/mplfinance/blob/master/src/mplfinance/_utils.py#L550-L551) and changed them from
```python
uh     = mcolors.to_rgba(marketcolors['candle']['up_hollow'], alpha)
dh     = mcolors.to_rgba(marketcolors['candle']['down_hollow'], alpha)
```
to
```python
uh     = mcolors.to_rgba(marketcolors['candle']['up'], 0.0)
dh     = mcolors.to_rgba(marketcolors['candle']['down'], 0.0)
```
With this approach we don't need `up_hollow` and `down_hollow` colors.  
(But, as I will discuss below, we still may want to implement them in certain situations).
This approach looks good with some styles, for example:

image
---
image
---
image
---
---
**The problem is that certain styles don't look so good with this approach.**
For example, the "default" mplfinance style that you used in your example:

image
---
As you can see above, there is almost **no** distinction between hollow and filled white candles, and there ***is*** **no** distinction between a hollow black and a hollow white.

---
* The general rule appears to be that *if a style has the ***same edge color for both up and down***, then the approach of setting* **`alpha=0.0`** *for hollow candes does not work with that particular style*.

---
I presently thinking of three possible ways to deal with styles that don't work well with `type='hollow_candle'`.  Let me know if you have any other ideas:
1. We can do nothing, and it is simply up to the user to choose a style (or customize their own) that works well with `type='hollow_candle'`.  Presently I am leaning towards this approach, at least on a first release, because it is simpler and we can see what kinds of feedback we get from people using hollow candles. 
2. Of the styles that don't work well with `type='hollow_candle'`, a common theme appears to be that the "Edge" color is the same for up and down candles.  We could consider that for hollow candles, if the style has Edge colors that are the same for up and down, then we automatically use the normal candle colors for the edges and wicks.  If we do this then the hollow candles will be correct, although their appearance may not be the best.  For example, for the 'default' style, the white candles are difficult to see (which is why that style gave them all a black outline to begin with) ...

| edge colors identical | edge color = candle color |
| -------- | ----- |
| image |  image |
---

Of course a user can always customize the style slightly, darkerning the face-color to be able to see the canldes better:

image
---

But this approach brings us back to the first idea, where the user is responsible to choose or customize a style that looks nice with hollow candles.

---
3. The third idea is to allow `up_hollow` and `down_hollow` tags in marketcolors.  If so, I am inclined to make them optional, and if not present then we take the first approach or the second approach.  One advantage of `up_hollow` and `down_hollow` is that it allows the user to use hollow colors that do not necessarily match the face-color of the plot.  This is what you did in your example.  A disadvantage is that it still leaves the user potentially open to the issue of edge colors being the same for up and down.  So this (idea number 3) could be combined with number 2 potentially.  Or again, the user can start with an existing style and customize it to look better with hollow candles.

### So please let me know what you think about all of the above.  
---

There is another issue, with the code, but it is somewhat independent so I will post it in a separate comment.

**Comment by DanielGoldfarb** [comment]
The *other* issue I mentioned has to do with a possible change to the code for  `_updownhollow_colors()`

When I said that I generated the charts above by simply modifying `_construct_hollow_candlestick_collections()` to set the **alpha** for the hollow colors to **0.0**, that wasn't entirely true.

When I first made the change to set the hollow colors alpha to zero, I noticed that my candles, in terms of which ones were hollow and which solid, did not completely match your example.  I looked carefully at the data and, while the colors were correct, I realized some of my candles were incorrect regarding being hollow (close > open) or solid (close < open).  I then took at close look at [**the code for _updownhollow_colors()**](https://github.com/KenanHArik/mplfinance/blob/master/src/mplfinance/_utils.py#L167-L177).

It seems to me that ([on line 175](https://github.com/KenanHArik/mplfinance/blob/master/src/mplfinance/_utils.py#L175)) the expression inside  `umap[cls > opn]` *should be the other way around*: **`umap[cls < opn]`**.  
*Both umap and dmap are deciding between **solid (`cls < opn`)** and **hollow**, and so the expression **should be the same in each***. 

When I made this change to line 175, my hollow_candle plots then matched yours, *and the data*, in terms of which candles should be hollow and which solid.  I can only think (without checking) that there is something in `style=hollow` (hollow.py) that compensates for this part of the code.  **Please let me know if you agree with me that it really should be `umap[cls < opn]`**

---

The other issue I found with `_updownhollow_colors()` is I think perhaps `first` should be determined from `umap` (not from `cmap`), 
so instead of:
```python
cmap = {True : upcolor, False : downcolor}
first = cmap[opens[0] < closes[0]]
umap = {True : upcolor, False : uphollow}
dmap = {True : downcolor, False : downhollow}
```
I propose this:
```python
umap = {True : upcolor, False : uphollow}
dmap = {True : downcolor, False : downhollow}
first = umap[opens[0] < closes[0]]
```
with no need for `cmap` at all in that function.

---
**Please let me know what you think of all of the above.**  Take your time.  Play with the code.

* I also want to say that you've done an *excellent job* keeping the code concise, elegant, and consistent with the existing code, and everything was placed right where it belongs.   Thank you!

* Just a reminder, you probably already know, if you push any changes to your fork, then, for as long as this Pull Request remains open, those changes will propagate into the Pull Request itself.  This is obviously a good thing facilitating any changes we agree to make before merging the pull request.  I'm just mentioning it because some people don't realize it.  Personally, it did suprise me the first time I made a PR.  I had thought that pushes to my fork would not get into the PR, and that I had to do something additional to get them there.

Thanks again.  All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
One last little thing.  You may have noticed, towards the bottom of this page, the "All checks have failed" message indicating that "The Travis CI build failed."   

If you you look at one of [**the logs**](https://travis-ci.org/github/matplotlib/mplfinance/jobs/752765025) pages ... at the very bottom of that log you will see the error message, `The command "/bin/bash scripts/check_version.sh $TRAVIS_PULL_REQUEST" exited with 1.`  

This is because we installed a script (`check_version.sh`) that checks to ensure that every PR bumps the version number by at least one notch.  [**You can find the version code here**](https://github.com/KenanHArik/mplfinance/blob/master/src/mplfinance/_version.py).

**Comment by KenanHArik** [comment]
Hi Daniel, Thank you for taking the time for reviewing the code so far, and your thoughtful comments.

When I first approached this, my thinking is how will the code support 4 different candle colors, because ultimately hollow candle style is exactly that. Whatever the style condition ends up being, there should be 4 distinct options. I did toy around with the idea of changing the edge color also dependent on whether it was a hollow candle, but realistically I personally wouldn't be looking for a style that does that.

I like your though about the alpha. It is an interesting approach, but interestingly enough, most of the hollow candle styles I see have regular up candles as hollow or white face, regular down color as red, down above close as black, and up below close as hollow red. Putting alpha on one of the channels would force the scheme of where 'hollow' would be. Perhaps others may want their regular up and down candles to be solids? :) I'm not sure as it is easy to be opinionated, and hard to judge what styles others may want.

As far as your first reply - I'm inclined to be leaning toward most of your first option, and some of your third. I do believe you hit the nail on the head that there are going to be some styles that just don't work well with hollow. On the other hand, I do think basic plotting may not want to worry about what a hollow color means when trying to figure out how to customize their styles. In my mind, it would be great if there was a hollow specific style sheet to abstract the choices away from someone not needing them. That is why I like aspects of your first option, and third. First because it would be good to get it in the hands of folks, and get their feedback and see what works well or needs tweaking as time goes on. As far as your third option, I would be inclined to believe that have the feature as optional to specify would be helpful. As I mentioned - I updated the style sheets 'just in case'... it was not really desirable. It would be great if there was just a default parameter that was over-ridable or such that could tweet the colors.

One thought for this is that _construct_hollow_candlestick_collections(...) in _utils.py could check to see if marketcolors has any hollow color keys to which it would use them if it did, or assign default style otherwise. This would allow styles to be more tailored to hollow verses not, and would keep style sheet more concise perhaps for folks less concerned about hollow candles. Additionally, this could potentially be implemented by adding a 'hollow' key to the marketcolors dictionary:

```
marketcolors  = {'candle'  : {'up':'w', 'down':'k'}, 
            'hollow' : {'up':'w', 'down':'k'},    # <------------ new key
            'edge'    : {'up':'k', 'down':'k'},
            'wick'    : {'up':'k', 'down':'k'},
            'ohlc'    : {'up':'k', 'down':'k'},
            'volume'  : {'up':'#181818', 'down':'#181818'},
            'vcedge'  : {'up':'#181818', 'down':'#181818'},
            'vcdopcod': False, # Volume Color is Per Price Change On Day
            'alpha'   : 0.9,
           },
```
What are your thoughts? Perhaps it is a simpler implementation and would not require changing style sheets unless there is an intent to plot hollow.

> It seems to me that ([on line 175](https://github.com/KenanHArik/mplfinance/blob/master/src/mplfinance/_utils.py#L175)) the expression inside `umap[cls > opn]` _should be the other way around_: **`umap[cls < opn]`**.
> _Both umap and dmap are deciding between **solid (`cls < opn`)** and **hollow**, and so the expression **should be the same in each**_.
> 
> When I made this change to line 175, my hollow_candle plots then matched yours, _and the data_, in terms of which candles should be hollow and which solid. I can only think (without checking) that there is something in `style=hollow` (hollow.py) that compensates for this part of the code. **Please let me know if you agree with me that it really should be `umap[cls < opn]`**
> 

This is a great observation. I intentionally did things backward in my approach, to make the standard up candle the hollow, and what would be the hollow up candle to be filled (it made sense at the time in my head). In hindsight, it makes sense to align it the way you mentioned. Really I should be assigning the regular candle up as transparent in the style, and for some reason my brain wasn't there when I was prototyping this. I will make this update.

> The other issue I found with `_updownhollow_colors()` is I think perhaps `first` should be determined from `umap` (not from `cmap`),
> so instead of:
> 
> ```python
> cmap = {True : upcolor, False : downcolor}
> first = cmap[opens[0] < closes[0]]
> umap = {True : upcolor, False : uphollow}
> dmap = {True : downcolor, False : downhollow}
> ```
> 
> I propose this:
> 
> ```python
> umap = {True : upcolor, False : uphollow}
> dmap = {True : downcolor, False : downhollow}
> first = umap[closes[0] < opens[0]]
> ```
> 

Completely agree 👍 I will update this.

> 
> * I also want to say that you've done an _excellent job_ keeping the code concise, elegant, and consistent with the existing code, and everything was placed right where it belongs.   Thank you!
> 

🙏  Thank you for the clean and organized code as the starting point! This means a lot to me. My background is in mechanical engineering, and here I am contributing to open source python project on plotting OHLCV data. 😅 This will be one of the first projects I'm contributing to on my own, so I'm still getting comfortable with certain aspects. It is great to contribute back!


> This is because we installed a script (`check_version.sh`) that checks to ensure that every PR bumps the version number by at least one notch. [**You can find the version code here**]

Thank you for that explanation. I was curious why I was seeing that, and didn't know what to make of it. Ironically, I rev'ed the version anyway later so that I could easily pip install from my fork. But that is a good note, because version change didn't cross my mind for a pipeline check.

I will implement the 2 small changes shortly, and will wait for your thoughts on approaching the marketcolors and style.

**Comment by KenanHArik** [comment]
One more note on this. After going deeper into the alpha, I found there is a bit of conflict because the alpha definition is a bit global. Since the paradigm of setting the regular up bars as transparent, and red hollow as transparent makes sense to me, the alpha setting will not work. Therefore, I created a alpha_handler function that takes in the color code, and checks to see if a lower alpha value was provided. If so, it allows it. With this, I set the default hollow style file to use RGBA tuple, which is allowed, and set the alpha to 0. This allows transparency of the candle without interfering with alpha when going through the alpha_handler function. Otherwise, without that function, it would set it to the global assigned alpha value.

Also - while I was in there, I went ahead and re-tuned the marketcolors to include a 'hollow' keyword as I was mentioning earlier. Now there is up and down for the hollow keyword of a stylesheet. See hollow.py in the styles.

After implementing the 2 proposed changes, I realized there was some error. The umap is a mapping up colors only, so I readjusted how first is calculated to not have to deal with another definition. Additionally, the relation between umap[cls > opn] and dmap[cls < opn] should be opposites I believe. For my definition, the up color and downcolor will be the same as candle up and down color definitions. Refer to the hollow.py style sheet for how this is mapped. I have followed this definition: https://allstarcharts.com/wp-content/uploads/2012/11/11-24-12-candles.png , please confirm if you agree with the definition / implimentaion.

```
umap = {True : upcolor, False : uphollow}
dmap = {True : downcolor, False : downhollow}
_list = [umap[cls > opn] if cls > cls0 else dmap[cls < opn] for opn0,cls0,opn,cls in zip(opens[0:-1],closes[0:-1],opens[1:],closes[1:]) ]
first = upcolor if closes[0] > opens[0] else downcolor
return [first] + _list
```

Thanks,
Kenan

**Comment by DanielGoldfarb** [comment]
Kenan,
I am a little bit confused/unclear what you mean by some of the statements in [your last comment](https://github.com/matplotlib/mplfinance/pull/309#issuecomment-755182023).  For example, it's not clear to me what this means:
>  I found there is a bit of conflict because the alpha definition is a bit global. Since the paradigm of setting the regular up bars as transparent, and red hollow as transparent makes sense to me, the alpha setting will not work.

None-the-less, later today I will read through your comment carefully and compare it to the code and perhaps I will get it.  **That said, please confirm, yes or no, whether all code changes you have mentioned in this comment have actually been pushed to your fork.  If any of the code changes you speak of are local to your machine, please put your current code somewhere that I can see it, so that we can be clear what we are talking about.**  Much appreciated.  I've always been of the opinion that the code itself is the ultimate documentation, and anytime a description or explanation is not clear to me, comparing it with the actual code usual makes it clear.  So I just want to verify that we are looking at, speaking about, the same code.  Thanks.

I have some other stuff to do and hope come back to this approximately 3 to 4 hours from now.

**Comment by DanielGoldfarb** [comment]
By the way, just to clarify some language that I have used, to again make sure we are understanding each other's terms, regarding your picture of the 4 color candlesticks here: https://allstarcharts.com/wp-content/uploads/2012/11/11-24-12-candles.png ...

I refer to the "hollow" versions as "transparent" (in the candle body) because the candle body, which you refer to as "white," is the same color as the background.  I'm not sure if this was a point of confusion between us or not.

If you google "hollow candlestick" and click on "Images" you will see many times the hollow candles are not white in the center, but are whatever color the face of the chart is.  **For example, see** [**here**](http://dragonflycap.com/hollow-red-candles/) or [**here**](https://www.freestockcharts.com/help/Content/Candlestick%20charts.htm).  

Again, I'm just trying to clarify whether or not we are using the same vocabulary (regarding terms such as "hollow", "transparent", "candle body" (vs "edge"), etc.).  To me, a candle that is "hollow" and one that has a "transparent" body are the same thing.  (That's not to say I am opposed to giving the user the power to simply choose any 4 colors to represent up-regular, down-regular, up-hollow, and down-hollow, where the hollow candles may have a body color that differs from the chart-face, *but* in the most common case there are typically only *two* colors but some of the candles are "hollow" (see-through or transparent).  I hope that makes sense.

Thanks.  --Daniel

**Comment by KenanHArik** [comment]
Hi Daniel, I can confirm that all the code changes have been pushed.

**Comment by KenanHArik** [comment]
Regarding the language clarification for hollow

> I refer to the "hollow" versions as "transparent" (in the candle body) because the candle body, which you refer to as "white," is the same color as the background. I'm not sure if this was a point of confusion between us or not.

:) this will be good to clarify, since there some overlap of terms. When I look for a hollow plotting style - the candles don't necessarily have to be transparent. They have to be able to take on a new color for the cases described in the 2 additional conditions to the diagram I sent. This is just to make more visually pronounced conditions for which there is a new down candle but relatively speaking _higher_ as well as a new up candle that is relatively speaking is _lower_. In my mind this adds 2 additional color variations over what regular candle plotting is capable of, bringing the total to 4. Having these 2 additional style spots is what I am referring to as a 'hollow' style, which in that regard is not the same as transparent. _Typically speaking, however,_ these will use transparent conditions for 2 of the cases, but I don't think it necessary required. Just a visual difference to pronounce these special cases of up and down candles that relatively speaking are not.

In the latest code I pushed - I think we should be able to copy all the google styles that you mentioned. The hollow style sheet should now look like this:

image

To make that I specified regular 'marketplace['candle']' up and down as transparent and red respectively. Then to take on the two additional stlyle variations for hollow, I added a 'marketplace['hollow'] up and down as transparent and  black respectively.... well at least that is how it displays. I realize as I type this that my definitions may need some swapping because in the style sheet it is 'oppositely' defined. Hopefully that doesn't lead to confusion for now. This can be quickly re-mapped to fix the labeling.

As a result of adding 'hollow' to the marketplace dictionary, I don't believe the other style sheets necessarily need to add it unless they want to incorporate it in their style. Perhaps only default and hollow need to the this key in their dictionary, and the other styles can persist without, or take on the default when it is not defined.

I hope that helps clarify. Thank you for your time.

**Comment by DanielGoldfarb** [comment]
Hi Kenan,
Thanks for the information.  I'm playing with the code, testing it, and experimenting with a couple different ways of doing things.  But I have some other things going on too, so it may be a few more days until I am ready to discuss this.  In the meantime, if you see on Github any notifications along the lines of "*DanielGoldfarb:hollow had recent pushes ...*" you can ignore them for now.  Certainly do ***not*** pull them into your branch as they are presently a **work in progress**.  I will touch base within two to four days, and then we can begin to move forward with this project.  Thanks for your patience.

**Comment by KenanHArik** [comment]
No worries. Thanks for the heads up and I will refrain from pulling.

Best,
Kenan

**Comment by DanielGoldfarb** [comment]
Hi Kenan,
I've gone through the code and run some tests, and I'm ready to discuss further.  I would like to ask if you will please send me an email at dgoldfarb.github@gmail.com so we can continue this discussion via email (and then post the final result here).  Or if you do not prefer that, let me know.  Thank you. --Daniel

**Pull request merged**
