### PR TITLE
prevent resizing candles in animation demos

### PR DESCRIPTION
**Pull request by mablue**
prevent candles resize

### CODE REVIEW

**Comment by DanielGoldfarb** [comment]
The issue here is *not* the resizing of candles, per se.  It is just that there are to ways typically to monitor/animate a plot:
1. Gradually increase the length of time displayed on the plot.  As we monitor/animate more and more data going forward in time, the amount of time represented by the x-axis gets larger, and the number of candles increases.  This necessarily requires that the candles gradually become smaller to be able to display the increased number of candles on the same plot.
2. Hold constant the time period displayed on the x-axis.  As we monitor/animate more data going foward in time, we drop old data, keeping the time window represented by the x-axis constant.  The number of candles displayed on the plot also remains constant.

The above two techniques are both valid, and which one a user chooses for any given plot depends on what the user has in mind to accomplish by that particular animation.

The [**code examples**](https://github.com/matplotlib/mplfinance/tree/master/examples) are meant to show users basic mplfinance techniques and various ways of doing things.  We should *not* change what these examples are showing.  *However, since the existing examples all represent technique numer 1 above, **it does seem worthwhile to add one or two examples showing technique number 2***.

If you would like to modify the code in your branch to
- leave the existing animation examples as they are, and
- add one or two ***new*** animation demo files, showing how to do "fixed time window" animation (for example, `mpf_animation_fixed_time_window_1.py` and `mpf_animation_fixed_time_window_2.py` as alternative versions of `mpf_animation_demo1.py` and `mpf_animation_demo2.py`)

then I will be happy to accept this Pull Request with said changes.

**Comment by mablue** [comment]
> The issue here is _not_ the resizing of candles, per se. It is just that there are to ways typically to monitor/animate a plot:
> 
> 1. Gradually increase the length of time displayed on the plot.  As we monitor/animate more and more data going forward in time, the amount of time represented by the x-axis gets larger, and the number of candles increases.  This necessarily requires that the candles gradually become smaller to be able to display the increased number of candles on the same plot.
> 2. Hold constant the time period displayed on the x-axis.  As we monitor/animate more data going foward in time, we drop old data, keeping the time window represented by the x-axis constant.  The number of candles displayed on the plot also remains constant.
> 
> The above two techniques are both valid, and which one a user chooses for any given plot depends on what the user has in mind to accomplish by that particular animation.
> 
> The [**code examples**](https://github.com/matplotlib/mplfinance/tree/master/examples) are meant to show users basic mplfinance techniques and various ways of doing things. We should _not_ change what these examples are showing. _However, since the existing examples all represent technique numer 1 above, **it does seem worthwhile to add one or two examples showing technique number 2**_.
> 
> If you would like to modify the code in your branch to
> 
> * leave the existing animation examples as they are, and
> * add one or two _**new**_ animation demo files, showing how to do "fixed time window" animation (for example, `mpf_animation_fixed_time_window_1.py` and `mpf_animation_fixed_time_window_2.py` as alternative versions of `mpf_animation_demo1.py` and `mpf_animation_demo2.py`)
> 
> then I will be happy to accept this Pull Request with said changes.

Thanks for your comprehensive responses. I want to do that yes. But I think you known that the main thing I want to do more complicated...
I need more plot types more datas and faster animating techniques to do my work I will talk some othere where with you...
This commit will be something like The first exercise to me to work with animations...
First of all I will say here I cant remove the first candle in fixed timeframe method as you can see. The first candle gradually shrinks and then disappears from the screen...:))
Second is that Its isolated process of animating a chart. But I need to control all steps without latency. I mean:
```
For i in range(100):
  mpl.cla()
  mpl.plot(df[i:i+10])
  time.sleep(1)
```
I want Something like this to control inside processes or maybe remove for loop  and split child statments of forloop to several functions and etc...

**Comment by DanielGoldfarb** [comment]
> First of all I will say here I cant remove the first candle in fixed timeframe method as you can see. The first candle gradually shrinks and then disappears from the screen...:))

Yes, I noticed that too.  It can be done, but would have to write a bunch of code; a little be complex but do-able.  I don't think it is worth the extra work it would take.

**Comment by mablue** [comment]
> > First of all I will say here I cant remove the first candle in fixed timeframe method as you can see. The first candle gradually shrinks and then disappears from the screen...:))
> 
> Yes, I noticed that too. It can be done, but would have to write a bunch of code; a little be complex but do-able. I don't think it is worth the extra work it would take.

worth? It can mean to me pure gold!!
Most awesome thing is that: ability to give an smaller timeframe to mpf and also give it a bigger timeframe and control it with steps like xlim:
mpl.plot(
   data=1min_dataframe, 
   resample='1h',
   window = (0,100),# to get first rows or window 100 to get last 100 rows
)

**Comment by DanielGoldfarb** [comment]
For now at least, I am closing this PR without merging.  As explained above it is beyond the scope of the needs of most mplfinance users; others are free to customize their own animation scripts (as was done here).

**Pull request closed without merging**
