### PR TITLE
add fill_between support for additional plot

### PR DESCRIPTION
**Pull request by wgong**

### CODE REVIEW

**Comment by DanielGoldfarb** [comment]
This looks good.   Thanks.   **Testing this code today.**

**Comment by wgong** [comment]
Thank you Mr Goldfarb, I like your pkg `mplfinance` and have built a small app at https://share.streamlit.io/wgong/streamlitapp/main/demos/demo_etf.py

**Comment by DanielGoldfarb** [comment]
@wgong  Thank you for sharing your app.  I've been playing with it.  It's very nice!   Great job!  I plan to play with it some more next week and read through the code so that I can understand it better.  I had not heard of streamlit;  it looks like a nice framework for quickly building apps.

Meanwhile, I am enhancing your mplfinance `fill_between` code to be able to accept a **`list` of `dicts`**, for multiple fill_between (something that people have been requesting for a while).  Thank you *very much* for contributing to mplfinance!

All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
**This PR was included in PR #529**

**Pull request closed without merging**
